FileVersion = 1

[Project]
Name = "cgltf-beef"
TargetType = "BeefLib"
StartupObject = "cgltf.Program"
DefaultNamespace = "cgltf"
ProcessorMacros = ["USE_SPAN"]

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/Debug-Win64/cgltf.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/Release-Win64/cgltf.lib"]
